
package com.asiainfo.axis2.client.jdk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "helloServicePortType", targetNamespace = "http://service.axis2.asiainfo.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServicePortType {


    /**
     * 
     * @param bt
     * @return
     *     returns java.lang.String
     * @throws HelloServiceUnsupportedEncodingException_Exception
     */
    @WebMethod(action = "urn:byteToString")
    @WebResult(targetNamespace = "http://service.axis2.asiainfo.com")
    @RequestWrapper(localName = "byteToString", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.ByteToString")
    @ResponseWrapper(localName = "byteToStringResponse", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.ByteToStringResponse")
    public String byteToString(
        @WebParam(name = "bt", targetNamespace = "http://service.axis2.asiainfo.com")
        byte[] bt)
        throws HelloServiceUnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:greeting")
    @WebResult(targetNamespace = "http://service.axis2.asiainfo.com")
    @RequestWrapper(localName = "greeting", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.Greeting")
    @ResponseWrapper(localName = "greetingResponse", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.GreetingResponse")
    public String greeting(
        @WebParam(name = "name", targetNamespace = "http://service.axis2.asiainfo.com")
        String name);

    /**
     * 
     * @param username
     * @return
     *     returns com.asiainfo.axis2.client.jdk.User
     */
    @WebMethod(action = "urn:getUser")
    @WebResult(targetNamespace = "http://service.axis2.asiainfo.com")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.GetUserResponse")
    public User getUser(
        @WebParam(name = "username", targetNamespace = "http://service.axis2.asiainfo.com")
        String username);

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "urn:hello")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void hello(
        @WebParam(name = "hello", targetNamespace = "http://service.axis2.asiainfo.com", partName = "parameters")
        Hello parameters);

    /**
     * 
     * @param str
     * @return
     *     returns byte[]
     * @throws HelloServiceUnsupportedEncodingException_Exception
     */
    @WebMethod(action = "urn:getBytes")
    @WebResult(targetNamespace = "http://service.axis2.asiainfo.com")
    @RequestWrapper(localName = "getBytes", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.GetBytes")
    @ResponseWrapper(localName = "getBytesResponse", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.GetBytesResponse")
    public byte[] getBytes(
        @WebParam(name = "str", targetNamespace = "http://service.axis2.asiainfo.com")
        String str)
        throws HelloServiceUnsupportedEncodingException_Exception
    ;

    /**
     * 
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:saveUser")
    @WebResult(targetNamespace = "http://service.axis2.asiainfo.com")
    @RequestWrapper(localName = "saveUser", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.SaveUser")
    @ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://service.axis2.asiainfo.com", className = "com.asiainfo.axis2.client.jdk.SaveUserResponse")
    public boolean saveUser(
        @WebParam(name = "user", targetNamespace = "http://service.axis2.asiainfo.com")
        User user);

}
