
package com.asiainfo.axis2.client.jdk;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "helloServiceUnsupportedEncodingException", targetNamespace = "http://service.axis2.asiainfo.com")
public class HelloServiceUnsupportedEncodingException_Exception
    extends Exception
{

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HelloServiceUnsupportedEncodingException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public HelloServiceUnsupportedEncodingException_Exception(String message, HelloServiceUnsupportedEncodingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public HelloServiceUnsupportedEncodingException_Exception(String message, HelloServiceUnsupportedEncodingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.asiainfo.axis2.client.jdk.HelloServiceUnsupportedEncodingException
     */
    public HelloServiceUnsupportedEncodingException getFaultInfo() {
        return faultInfo;
    }

}
